const axios = require('axios');
require('dotenv').config();

const API_URL = process.env.PAYCHANGU_API_URL || 'https://api.paychangu.com';
const SECRET_KEY = process.env.PAYCHANGU_SECRET_KEY;

const apiClient = axios.create({
    baseURL: API_URL,
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SECRET_KEY}` // Assuming Bearer token based on standard practices
    }
});

/**
 * Get supported mobile money operators
 */
exports.getMobileMoneyOperators = async () => {
    try {
        const response = await apiClient.get('/mobile-money');
        // PayChangu returns { status: 'success', data: [...] }
        // We only want the array
        return response.data.data || [];
    } catch (error) {
        console.error('PayChangu getOperators Error:', error.response?.data || error.message);
        throw error;
    }
};

/**
 * Initiate a mobile money payment
 * @param {Object} data - Payment details
 * @param {string} data.mobile_money_operator_ref_id - Operator Ref ID
 * @param {string} data.mobile - Mobile number
 * @param {number} data.amount - Amount to charge
 * @param {string} data.charge_id - Unique charge ID (optional, or generated by PayChangu?)
 * Note: PayChangu API usually takes mobile, amount, operator_ref_id.
 * Based on user snippet: body: { mobile_money_operator_ref_id: '...' }
 * But we also need amount and phone number.
 * Checking standard PayChangu docs or user snippets:
 * User snippet 1: body: { mobile_money_operator_ref_id: '...' } -> This looks incomplete for a payment init.
 * User snippet 3: paychangu.chargeMobileMoney({ mobile_money_operator_ref_id: '...' })
 * 
 * Let's assume the standard payload:
 * {
 *   mobile: "...",
 *   amount: "...",
 *   mobile_money_operator_ref_id: "..."
 * }
 */
exports.initiatePayment = async (paymentData) => {
    const crypto = require('crypto');
    try {
        // Format mobile number: PayChangu expects 9 digits (265 prefix removed)
        let formattedMobile = paymentData.mobile.replace(/\D/g, ''); // Remove non-digits

        // Handle 265 prefix (12 digits) -> strip 265
        if (formattedMobile.startsWith('265') && formattedMobile.length === 12) {
            formattedMobile = formattedMobile.substring(3);
        }
        // Handle 0 prefix (10 digits) -> strip 0
        else if (formattedMobile.startsWith('0') && formattedMobile.length === 10) {
            formattedMobile = formattedMobile.substring(1);
        }

        // Create a unique charge_id if not provided
        const chargeId = paymentData.charge_id || crypto.randomUUID();

        // Construct payload
        const payload = {
            mobile: formattedMobile,
            amount: paymentData.amount,
            mobile_money_operator_ref_id: paymentData.mobile_money_operator_ref_id,
            charge_id: chargeId
        };

        const response = await apiClient.post('/mobile-money/payments/initialize', payload);

        // Ensure we return the charge_id so controller can save it
        return { ...response.data, charge_id: chargeId };
    } catch (error) {
        console.error('PayChangu initiatePayment Error:', error.response?.data || error.message);
        throw error;
    }
};

/**
 * Verify a payment
 * @param {string} chargeId - The charge ID to verify
 */
exports.verifyPayment = async (chargeId) => {
    try {
        const response = await apiClient.get(`/mobile-money/payments/${chargeId}/verify`);
        return response.data;
    } catch (error) {
        console.error('PayChangu verifyPayment Error:', error.response?.data || error.message);
        throw error;
    }
};

/**
 * Initiate a payout to a mobile money account
 * @param {Object} data - Payout details
 * @param {string} data.mobile - Mobile number to receive the money
 * @param {string} data.mobile_money_operator_ref_id - Operator Ref ID
 * @param {number} data.amount - Amount to send
 * @param {string} data.charge_id - Unique charge ID for this payout
 * @param {string} data.email - Optional email
 * @param {string} data.first_name - Optional first name
 * @param {string} data.last_name - Optional last name
 */
exports.initiatePayout = async (payoutData) => {
    try {
        // Format mobile number: PayChangu expects 9 digits (265 prefix removed)
        let formattedMobile = payoutData.mobile.replace(/\D/g, ''); // Remove non-digits

        // Handle 265 prefix (12 digits) -> strip 265
        if (formattedMobile.startsWith('265') && formattedMobile.length === 12) {
            formattedMobile = formattedMobile.substring(3);
        }
        // Handle 0 prefix (10 digits) -> strip 0
        else if (formattedMobile.startsWith('0') && formattedMobile.length === 10) {
            formattedMobile = formattedMobile.substring(1);
        }

        const payload = {
            mobile: formattedMobile,
            amount: payoutData.amount,
            mobile_money_operator_ref_id: payoutData.mobile_money_operator_ref_id,
            charge_id: payoutData.charge_id,
            email: payoutData.email,
            first_name: payoutData.first_name,
            last_name: payoutData.last_name
        };

        console.log('💸 [PayChangu] Initiating payout with payload:', JSON.stringify(payload, null, 2));

        const response = await apiClient.post('/mobile-money/payouts/initialize', payload);

        console.log('✅ [PayChangu] Payout response:', JSON.stringify(response.data, null, 2));
        return response.data;
    } catch (error) {
        console.error('❌ [PayChangu] initiatePayout Error - Full Details:', JSON.stringify({
            status: error.response?.status,
            statusText: error.response?.statusText,
            data: error.response?.data,
            message: error.message
        }, null, 2));
        throw error;
    }
};

