const axios = require('axios');
require('dotenv').config();

const API_URL = process.env.PAYCHANGU_API_URL || 'https://api.paychangu.com';
const SECRET_KEY = process.env.PAYCHANGU_SECRET_KEY;

const apiClient = axios.create({
    baseURL: API_URL,
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SECRET_KEY}` // Assuming Bearer token based on standard practices
    }
});

/**
 * Get supported mobile money operators
 */
exports.getMobileMoneyOperators = async () => {
    try {
        const response = await apiClient.get('/mobile-money');
        return response.data;
    } catch (error) {
        console.error('PayChangu getOperators Error:', error.response?.data || error.message);
        throw error;
    }
};

/**
 * Initiate a mobile money payment
 * @param {Object} data - Payment details
 * @param {string} data.mobile_money_operator_ref_id - Operator Ref ID
 * @param {string} data.mobile - Mobile number
 * @param {number} data.amount - Amount to charge
 * @param {string} data.charge_id - Unique charge ID (optional, or generated by PayChangu?)
 * Note: PayChangu API usually takes mobile, amount, operator_ref_id.
 * Based on user snippet: body: { mobile_money_operator_ref_id: '...' }
 * But we also need amount and phone number.
 * Checking standard PayChangu docs or user snippets:
 * User snippet 1: body: { mobile_money_operator_ref_id: '...' } -> This looks incomplete for a payment init.
 * User snippet 3: paychangu.chargeMobileMoney({ mobile_money_operator_ref_id: '...' })
 * 
 * Let's assume the standard payload:
 * {
 *   mobile: "...",
 *   amount: "...",
 *   mobile_money_operator_ref_id: "..."
 * }
 */
exports.initiatePayment = async (paymentData) => {
    try {
        // Construct payload
        const payload = {
            mobile: paymentData.mobile,
            amount: paymentData.amount,
            mobile_money_operator_ref_id: paymentData.mobile_money_operator_ref_id,
            // Add other required fields if any, e.g., email, name if needed
        };

        const response = await apiClient.post('/mobile-money/payments/initialize', payload);
        return response.data;
    } catch (error) {
        console.error('PayChangu initiatePayment Error:', error.response?.data || error.message);
        throw error;
    }
};

/**
 * Verify a payment
 * @param {string} chargeId - The charge ID to verify
 */
exports.verifyPayment = async (chargeId) => {
    try {
        const response = await apiClient.get(`/mobile-money/payments/${chargeId}/verify`);
        return response.data;
    } catch (error) {
        console.error('PayChangu verifyPayment Error:', error.response?.data || error.message);
        throw error;
    }
};

/**
 * Initiate a payout to a mobile money account
 * @param {Object} data - Payout details
 * @param {string} data.mobile - Mobile number to receive the money
 * @param {string} data.mobile_money_operator_ref_id - Operator Ref ID
 * @param {number} data.amount - Amount to send
 * @param {string} data.charge_id - Unique charge ID for this payout
 * @param {string} data.email - Optional email
 * @param {string} data.first_name - Optional first name
 * @param {string} data.last_name - Optional last name
 */
exports.initiatePayout = async (payoutData) => {
    try {
        const payload = {
            mobile: payoutData.mobile,
            amount: payoutData.amount,
            mobile_money_operator_ref_id: payoutData.mobile_money_operator_ref_id,
            charge_id: payoutData.charge_id,
            email: payoutData.email,
            first_name: payoutData.first_name,
            last_name: payoutData.last_name
        };

        const response = await apiClient.post('/mobile-money/payouts/initialize', payload);
        return response.data;
    } catch (error) {
        console.error('PayChangu initiatePayout Error:', error.response?.data || error.message);
        throw error;
    }
};

